[proxmox-backup-server]
enabled   = true
port      = 8007
filter    = proxmox-backup-server
logpath   = /var/log/proxmox-backup/api/auth.log
maxretry  = 2
findtime  = 30m
bantime   = 6h
banaction = iptables-allports
ignoreip  = 127.0.0.1/8 ::1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
bantime.increment = true
bantime.overalljails = true
bantime.factor = 6
bantime.maxtime = 1w
action    = %(action_)s
           telegram

[sshd]
action    = %(action_)s
           telegram

[proxmox-backup-server-recidive]
enabled   = false
filter    = fail2ban
logpath   = /var/log/fail2ban.log
banaction = iptables-allports
maxretry  = 3
findtime  = 1d
bantime   = 1w
ignoreip  = 127.0.0.1/8 ::1
